__ANN Classification__

In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

import pickle

In [3]:
### load the dataset

data = pd.read_csv("Churn_Modelling.csv")

In [4]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
### preprocess the data

data = data.drop(['RowNumber', 'CustomerId', "Surname"], axis=1)

In [6]:
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [7]:
### Encoding the following categorical variable

label_encoder_gender = LabelEncoder()

In [8]:
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [9]:
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [10]:
## converting the geography column to one hot encoding

from sklearn.preprocessing import OneHotEncoder

In [12]:
one_hot_encoder_geo = OneHotEncoder()

In [13]:
geo_encoder = one_hot_encoder_geo.fit_transform(data[['Geography']])

In [14]:
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [16]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [15]:
one_hot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [18]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(), columns = one_hot_encoder_geo.get_feature_names_out(['Geography']))

In [19]:
geo_encoder_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [20]:
### combine one hot encoded columns with the original data

data = pd.concat([data.drop('Geography', axis=1), geo_encoder_df], axis = 1)

In [21]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [22]:
### saving encoders and scaler as pickle file

with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('one_hot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder_geo, file)

In [23]:
### divide the dataset into dependent and independent feature

data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [24]:
X = data.drop('Exited', axis = 1)
y = data['Exited']

In [25]:
X

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 12 columns]

In [26]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [27]:
### splitting the data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
### scaling the following terms

scaler = StandardScaler()

In [29]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [31]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [32]:
## dumping pkl files

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### ANN Implementation

In [33]:
import tensorflow as tf

from tensorflow.keras.models import Sequential  #type: ignore
from tensorflow.keras.layers import Dense   #type: ignore
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard   #type: ignore

import datetime

In [35]:
X_train.shape[1]

12

In [36]:
### build our ANN model

model = Sequential([
    Dense(64, activation = 'relu', input_shape = (X_train.shape[1], )),    ### HL1 connected with input layer
    Dense(32, activation='relu'),  ## HL2
    Dense(1, activation='sigmoid')  ## output layer
])

WARNING:tensorflow:From s:\ANN Classification\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
import tensorflow

opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [40]:
loss

In [41]:
## compile the model

model.compile(optimizer = opt, loss = "binary_crossentropy", metrics = ['accuracy'])

In [57]:
### set u the tensor board

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [58]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard  #type: ignore

tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [59]:
### set up Early Stopping

early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [60]:
### training the model

history = model.fit(
    X_train, y_train, validation_data=(X_test, y_test), epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3350 - accuracy: 0.8612 - val_loss: 0.3459 - val_accuracy: 0.8650
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3307 - accuracy: 0.8634 - val_loss: 0.3428 - val_accuracy: 0.8610
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3303 - accuracy: 0.8660 - val_loss: 0.3441 - val_accuracy: 0.8640
Epoch 4/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3272 - accuracy: 0.8658 - val_loss: 0.3505 - val_accuracy: 0.8595
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3264 - accuracy: 0.8649 - val_loss: 0.3428 - val_accuracy: 0.8610
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3254 - accuracy: 0.8669 - val_loss: 0.3464 - val_accuracy: 0.8655
Epoch 7/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3230 - accuracy: 0.8660 - val_loss: 0.3384 - val_accuracy: 0.8645
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3179 - accuracy: 0.8705 - val_loss: 0.3466 - val_accuracy: 0.8630
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3196 - accuracy: 0.8700 - val_loss: 0.3491 - val_accuracy: 0.8685
Epoch 10/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3143 - accuracy: 0.8708 - val_loss: 0.3491 - val_accuracy: 0.8640
Epoch 11/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3146 - accuracy: 0.8716 - val_loss: 0.3664 - val_accuracy: 0.8660
Epoch 12/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3128 - accuracy: 0.8711 - val_loss: 0.3485 - val_accuracy: 0.8660
Epoch 13/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3084 - accuracy: 0.8740 - val_loss: 0.3518 - val_accuracy: 0.8685
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3096 - accuracy: 0.8709 - val_loss: 0.3607 - val_accuracy: 0.8645
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3045 - accuracy: 0.8706 - val_loss: 0.3603 - val_accuracy: 0.8630
Epoch 16/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3027 - accuracy: 0.8727 - val_loss: 0.3695 - val_accuracy: 0.8620
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 0.2993 - accuracy: 0.8731 - val_loss: 0.3605 - val_accuracy: 0.8695

In [61]:
model.save('model.h5')

s:\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [62]:
### Load tensorBoard Extension

%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [64]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 11888), started 0:27:05 ago. (Use '!kill 11888' to kill it.)